// refresh after 2 weeks
export const STORAGE_REFRESH_INTERVAL = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000);

export const KNOWN_DOMAINS = [
  'reddit.com',
  'wikipedia.org',
  'cnn.com',
  'bbc.co.uk',
  'ycombinator.com',
  'itch.io',
  'github.com',
  'tvtropes.org',
  'github.io',
  'npr.org',
  'metacritic.com',
  'steampowered.com',
  'huggingface.co',
  'linkedin.com',
  'stackoverflow.com',
  'stackexchange.com',
];

export const KNOWN_SHORTENERS = [
  'bit.ly',
  'lnkd.in',
  'goo.gl',
  't.co',
  'ow.ly',
  'tinyurl.com',
  'buff.ly',
  'trib.al',
  'is.gd',
  'tiny.cc',
  'dlvr.it',
  'shar.es',
  'su.pr',
  'fur.ly',
  'u.nu',
  'qr.ae',
  'adf.ly',
  'bit.do',
  'mcaf.ee',
  'cli.gs',
  'yfrog.com',
  'tinyarrows.com',
  'snipurl.com',
  'short.to',
  'bc.vc',
  'twitthis.com',
  'u.to',
  'j.mp',
];

// list out typical URL tracking query param prefixes like `utm_` and `fb_`
export const KNOWN_TRACKING_PARAM_PREFIXES = [
  'utm_',
  'fb_',
  'gclid',
  'msclkid',
  'mc_cid',
  'mc_eid',
  'mc_lid',
  'mc_mid',
  'mc_rid',
  'mc_t',
  'mc_uid',
];
