create table "public"."expanded_urls" (
    "id" bigint generated by default as identity not null,
    "expanded_url" text,
    "short_url" text,
    "provider_id" bigint,
    "metadata" json,
    "screenshot" text,
    "favicon" text,
    "snapshot" text,
    "last_updated" timestamp with time zone not null default now()
);


alter table "public"."expanded_urls" enable row level security;

CREATE UNIQUE INDEX expanded_urls_pkey ON public.expanded_urls USING btree (id);

alter table "public"."expanded_urls" add constraint "expanded_urls_pkey" PRIMARY KEY using index "expanded_urls_pkey";

grant delete on table "public"."expanded_urls" to "anon";

grant insert on table "public"."expanded_urls" to "anon";

grant references on table "public"."expanded_urls" to "anon";

grant select on table "public"."expanded_urls" to "anon";

grant trigger on table "public"."expanded_urls" to "anon";

grant truncate on table "public"."expanded_urls" to "anon";

grant update on table "public"."expanded_urls" to "anon";

grant delete on table "public"."expanded_urls" to "authenticated";

grant insert on table "public"."expanded_urls" to "authenticated";

grant references on table "public"."expanded_urls" to "authenticated";

grant select on table "public"."expanded_urls" to "authenticated";

grant trigger on table "public"."expanded_urls" to "authenticated";

grant truncate on table "public"."expanded_urls" to "authenticated";

grant update on table "public"."expanded_urls" to "authenticated";

grant delete on table "public"."expanded_urls" to "service_role";

grant insert on table "public"."expanded_urls" to "service_role";

grant references on table "public"."expanded_urls" to "service_role";

grant select on table "public"."expanded_urls" to "service_role";

grant trigger on table "public"."expanded_urls" to "service_role";

grant truncate on table "public"."expanded_urls" to "service_role";

grant update on table "public"."expanded_urls" to "service_role";


