name: Continuous Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # borrowed from: https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/20
  # fail_if_pull_request_is_draft:
  #   if: github.event.pull_request.draft == true
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Fail in order to indicate that Pull Request needs to be marked as Ready for Review before CI/CD pipeline can run.
  #     run: exit 1

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global user.email "bot@interweb.wtf"
          git config --global user.name "Interweb.WTF Release Bot"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check for modified files
        id: git-check
        run: value=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
          echo "modified=$value" >> $GITHUB_OUTPUT

      - name: Run Tests
        run: npm test

      # - name: PR Preview Deployment
      #   uses: amondnet/vercel-action@v20
      #   id: vercel-action-pr
      #   if: startsWith(github.head_ref, 'feature/') && github.base_ref == 'main'
      #   with:
      #     vercel-project-name: work-with-me
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     github-token: ${{ secrets.GH_AUTH_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      #     scope: interweb-alchemy
      #     alias-domains: |
      #       pr-{{PR_NUMBER}}-work-with-me.vercel.app

      - name: Deploy to Production
        uses: amondnet/vercel-action@v20
        id: vercel-action-production
        if: github.ref == 'refs/heads/main'
        with:
          vercel-project-name: work-with-me
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_AUTH_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: '--prod'
          scope: interweb-alchemy
          alias-domains: |
            interweb-wtf.vercel.app

      - name: Push Changes to Type Definitions
        if: steps.git-check.outputs.modified == 'true'
        run: |

          git add .
          git commit -m 'chore(types): update supabase type definitions'
          git push origin HEAD:main

      - name: Semantic Release
        if: github.ref == 'refs/heads/main'
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
